# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
#org.gradle.jvmargs=
org.gradle.daemon=false
org.gradle.debug=false

## Environment Properties

minecraft_version=1.20.4
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=work_orders
# The human-readable display name for the mod.
mod_name=Work Orders
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=MIT
# The mod version. See https://semver.org/
mod_version=1.1.0
mod_group_id=gay.skyebound.work_orders
mod_authors=Skylar G.
mod_description=A vanilla-style mod that adds limited-time villager trades.
pack_format_number=18

## Dependencies

midnightlib_version=1.5.2-neoforge
fabric_api_version=0.97.3+1.20.4
