# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=work_orders
# The human-readable display name for the mod.
mod_name=Work Orders
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=MIT
# The mod version. See https://semver.org/
mod_version=1.2.0
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
maven_group=com.skyegallup.work_orders
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=Skylar Gallup
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=A vanilla-style mod that adds limited-time villager trades.
# Pack version - this changes each minecraft release, in general.
pack_format_number=18
archives_name = work_orders
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.20.4

# Dependencies
architectury_api_version = 11.1.17
fabric_loader_version = 0.19.5
fabric_api_version = 0.97.3+1.20.4
neoforge_version = 20.4.251
# Specify other mod dependencies in each subprojects' Gradle configs
