modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/skyegallup/work-orders/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/mod/work-orders"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="work_orders.mixins.json"

[[accessTransformers]]
file="work_orders_base.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="midnightlib"
    mandatory=true
    versionRange="[1.5.2,)"
    side="CLIENT"
