modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId="work_orders"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/mod/work-orders"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.work_orders]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.work_orders]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.work_orders]]
modId = "architectury"
type = "required"
versionRange = "[13.0.11,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.work_orders]]
modId = "midnightlib"
type = "required"
versionRange = "[1.7.5,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "work_orders.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
